language: node_js
node_js:
- 9.3.0
branches:
  only:
  - develop
before_install:
- export TZ=Asia/Shanghai

- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
before_script:
- git config --global user.name 'realXuJiang'
- git config --global user.email 'realJiangXu@gmail.com'
- git clone --depth=1 git@github.com:realXuJiang/hexo-theme-replica.git themes/replica
- git clone git@github.com:itweet/itweet.github.io.git -b master --single-branch .deploy_git
script:
- npm run build
after_success:
- npm run deploy
itweet/itweet.github.io:
- openssl aes-256-cbc -K $encrypted_f1a73abf056e_key -iv $encrypted_f1a73abf056e_iv
  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d