language: node_js
node_js:
  - 9.3.0
branches:
  only:
  - develop
before_install:
- export TZ=Asia/Shanghai
# Decrypt the private key
- openssl aes-256-cbc -K $encrypted_e68f6daeeb7a_key -iv $encrypted_e68f6daeeb7a_iv
  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
# Set the permission of the key
- chmod 600 ~/.ssh/id_rsa
# Start SSH agent
- eval $(ssh-agent)
# Add the private key to the system
- ssh-add ~/.ssh/id_rsa
# Copy SSH config
- cp .travis/ssh_config ~/.ssh/config
before_script:
# Set Git config
- git config --global user.name 'realXuJiang'
- git config --global user.email 'realJiangXu@gmail.com'

# Clone the repository
- git clone --depth=1 git@github.com:realXuJiang/hexo-theme-replica.git themes/replica
##clone gh-pages branch only, into .deploy_git folder, so that commit history can be kept
- git clone git@github.com:itweet/itweet.github.io.git -b develop --single-branch .deploy_git
script:
- npm run build
after_success:
- npm run deploy
itweet/itweet.github.io:

